### ISSUE TITLE
TypeError: default_drivelm() missing 1 required positional argument: 'ann_paths'

### ISSUE THREAD

**Issue by MlLearnerAkash** [OpenDriveLab/ELM#7]
Below attaching the full log:
```
Using downloaded and verified file: /home/pravaig-20/ELM/lavis/.././data/drivelm/train.json
Using downloaded and verified file: /home/pravaig-20/ELM/lavis/.././data/drivelm/val.json
Using downloaded and verified file: /home/pravaig-20/ELM/lavis/.././data/drivelm/val.json
2024-04-03 10:44:16,614 [INFO] Building datasets...
Traceback (most recent call last):
  File "scripts/train.py", line 112, in <module>
    main()
  File "scripts/train.py", line 104, in main
    datasets = task.build_datasets(cfg)
  File "/home/pravaig-20/ELM/lavis/tasks/vqa.py", line 74, in build_datasets
    datasets = super().build_datasets(cfg)
  File "/home/pravaig-20/ELM/lavis/tasks/base_task.py", line 57, in build_datasets
    dataset = builder.build_datasets()
  File "/home/pravaig-20/ELM/lavis/datasets/builders/base_dataset_builder.py", line 58, in build_datasets
    datasets = self.build()  # dataset['train'/'val'/'test']
  File "/home/pravaig-20/ELM/lavis/datasets/builders/base_dataset_builder.py", line 228, in build
    datasets[split] = dataset_cls(
  File "/home/pravaig-20/ELM/lavis/datasets/datasets/elm_datasets.py", line 84, in __init__
    self.default_drivelm()
TypeError: default_drivelm() missing 1 required positional argument: 'ann_paths'

```

**Comment by DevLinyan** [comment]
Hi, thanks for pointing it out. We have fixed it. Please update your code accordingly. You can adjust the path to your dataset in this [file](https://github.com/OpenDriveLab/ELM/blob/04666d3691a9b1e3351b4605a27dedcdb6967d11/lavis/projects/blip2/train/advqa_t5_elm.yaml#L37) as needed.

**Comment by MlLearnerAkash** [comment]
Thanks @DevLinyan, after pulling it solved the issue.
